version: '3'
services:
  flask-app:
    image: dti:v0.1
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb
    command: ["python", "app.py"]    

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:


