name: Push Event Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Go
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build Go
        run: go build -v hello_world.go

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test go
        run: go test hello_world_test.go hello_world.go

  cleanup:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create a text file
        run: touch file.txt
      - name: List runner
        run: ls /home/runner/
      - name: cleanup
        run: chmod +x cleanup.sh && ./cleanup.sh
