name: Push Event Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Go
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build Go
        run: go build -v hello_world.go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test go
        run: go test hello_world_test.go hello_world.go
